Больше функций
htmlacademy-javascript/887399-kekstagram-22 pull request #2
Opened 2021-02-15 12:47 UTC by ratroian

2021-02-15 13:20 UTC, svoboda-rabstvo commented on js/main.js
> +  if (workString.length <= maxLength) {
Здесь можно немного улучшить условие на `return workString.length <= maxLength`

2021-02-15 13:20 UTC, svoboda-rabstvo commented on js/main.js
> +let randomInteger = function (min, max) {
Функции лучше всего записывать как `const` т.к. они в дальнейшем не меняются

2021-02-15 13:21 UTC, svoboda-rabstvo commented on js/main.js
> +    let rand = min - 0.5 + Math.random() * (max - min + 1);
Если переменная больше нигде не меняется то её лучше определять как `const`

2021-02-15 13:22 UTC, svoboda-rabstvo commented on js/main.js
> +let minValue = 1;
Это константы которые используются в дальнейшей программе их принято писать капслоком и через нижнее подчеркивание. `MIN_VALUE` & `MAX_VALUE`

2021-02-15 13:22 UTC, svoboda-rabstvo commented on js/main.js
> +let randomInteger = function (min, max) {
Пробегись по функциям таким в файле и поправь плз :)

2021-02-15 13:23 UTC, svoboda-rabstvo commented on js/main.js
> +    let rand = min - 0.5 + Math.random() * (max - min + 1);
Пробегись по переменным таким в файле и поправь плз :)

2021-02-15 13:24 UTC, svoboda-rabstvo commented on js/main.js
> +let stringComment = ('Определенное количество символов');
Здесь можно обойтись без скобок, работать тоже будет ок :) Но небольшая ошибка в `let` и `const`. Тут лучшего всего использовать `const`

2021-02-15 13:24 UTC, svoboda-rabstvo requested changes
LGTM, но нужно поправить использование `const` & `let` и название констант :)

2021-02-15 16:25 UTC, ratroian commented on js/main.js
> +let randomInteger = function (min, max) {
Ок,  понял

2021-02-15 16:28 UTC, ratroian commented on js/main.js
> +    let rand = min - 0.5 + Math.random() * (max - min + 1);
т.е. переменные с математическими выражениями всегда лучше определять как const? И не совсем понял - как в начале кода определять будет ли меняться переменная? Может есть какие-то рекомендации или что-то вроде того?))

2021-02-15 16:35 UTC, ratroian commented on js/main.js
> +let minValue = 1;
Ее нужно и переопределить как const?

2021-02-15 17:20 UTC, ratroian commented on js/main.js
> +  if (workString.length <= maxLength) {
ok

2021-02-15 19:30 UTC, svoboda-rabstvo commented on js/main.js
> +    let rand = min - 0.5 + Math.random() * (max - min + 1);
Если переменная не меняется в дальнейшем, то всегда используется `const`. Если меняется тогда `let`

2021-02-15 19:30 UTC, svoboda-rabstvo commented on js/main.js
> +let minValue = 1;
Ага

2021-02-16 11:30 UTC, svoboda-rabstvo approved these changes
LGTM

2021-02-16 11:31 UTC, merged